version: "3.8"

services:
  iprwc:
    container_name: iprwc-webshop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iprwc-do-user-18873855-0.k.db.ondigitalocean.com:25060/iprwc?sslmode=require
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_KNUmdVRDHjGAHDw3-G1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
